'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
const number=(v:any,unit:string)=>typeof v==='number'?`${v.toLocaleString(undefined,{maximumFractionDigits:2})} ${unit}`:'Unassigned';
const words=(v:string)=>v.replaceAll('_',' ');
const source=(url:string)=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:undefined;}catch{return undefined;}};
export default function EquipmentMatches({requirements,report,dirty,busy,searching,onRefresh}:{requirements?:any;report?:any;dirty:boolean;busy:boolean;searching:boolean;onRefresh:()=>void}){
 const [expanded,setExpanded]=useState(false);
 const ready=!!requirements?.ready_for_matching;
 const rows=report?.items||[];
 const byId=new Map<string,any>((requirements?.requirements||[]).map((r:any)=>[r.id,r]));
 return <section className="equipment-matches" aria-label="Equipment matches for this reference design"><div className="equipment-heading"><div><h3>Equipment for this design</h3><p>RD calculates equipment duties in both sizing modes. Manual mode keeps your commercial pipe sizes; Preliminary mode rounds sizes from flow. The headless finder searches its current catalogue.</p></div><Button variant="outline" disabled={!ready||dirty||busy} onClick={onRefresh}>{searching?'Finding equipment…':'Refresh equipment matches'}</Button></div>
 {dirty?<p>Apply the current parameters to match equipment to this design.</p>:!ready?<p>Apply design to calculate duties at the chosen pipe sizes. If requirements remain unresolved, review the sizing findings; changing the reference preset is not required.</p>:searching?<p role="status">Reading the current finder catalogue and comparing it with RD’s applied requirements…</p>:report?.status==='unavailable'?<p role="alert">{report.message}</p>:report?.status==='complete'?<><p className="equipment-summary" role="status">{report.summary.with_candidates} of {report.summary.items} component duties have candidates · {report.summary.unresolved} require further information or sourcing.</p><p className="equipment-revision">Catalogue checked {new Date(report.catalogue.fetched_at).toLocaleString()} · {report.catalogue.row_count} records · snapshot {report.catalogue.sha256.slice(0,12)}. Database updates appear on the next search.</p>
 <details><summary>Review calculated requirements and candidate parts</summary><div className="sizing-table"><table><thead><tr><th>Component / circuit</th><th>RD requirement</th><th>Finder result</th></tr></thead><tbody>{(expanded?rows:rows.slice(0,30)).map((row:any)=>{const r=byId.get(row.id);return <tr key={row.id}><td><strong>{row.component_id}</strong><small>{words(row.kind||row.category)} · {row.circuit_ids.join(', ')}</small></td><td>{r?.thermal_duty&&<div>{number(r.thermal_duty.required_capacity_W/1000,'kW')}</div>}{r?.throttling&&<div>Kv {number(r.throttling.required_Kv_m3_h,'m³/h')}</div>}{r?.fluid_sides?.map((s:any)=><div key={s.circuit_id}>{s.service}: {number(s.design_flow_m3_s==null?null:s.design_flow_m3_s*60000,'L/min')}<small>Minimum rating: {number(s.minimum_pressure_rating_Pa==null?null:s.minimum_pressure_rating_Pa/100000,'bar')} · {number(s.temperature?.required_max_temperature_C,'°C')}</small></div>)}<small>NPS {[...new Set((r?.ports||[]).map((p:any)=>p.nominal_nps_in).filter((x:any)=>x!=null))].join(', ')||'unassigned'} in</small></td><td>{row.candidates.length?row.candidates.map((candidate:any)=><div className="equipment-candidate" key={candidate.component.part_number}><strong>{candidate.component.brand} · {candidate.component.part_number}</strong><small>{candidate.status==='qualified'?'Declared duty screen passed':'Tentative · qualification incomplete'}</small><details><summary>Source and qualifications</summary><p>{candidate.component.component_name}</p><p>{candidate.component.source_catalog} · {candidate.component.source_page}</p>{source(candidate.component.datasheet_url)&&<a href={source(candidate.component.datasheet_url)} target="_blank" rel="noreferrer">Vendor source</a>}{candidate.limitations.map((line:string,i:number)=><p key={i}>{line}</p>)}</details></div>):<span>No suitable candidate in this catalogue.</span>}<details><summary>Unresolved requirements</summary>{[...(r?.unresolved||[]).map((u:any)=>u.detail),...(row.unresolved||[])].map((line:string,i:number)=><p key={i}>{line}</p>)}</details></td></tr>;})}</tbody></table></div>{rows.length>30&&<Button variant="ghost" onClick={()=>setExpanded(v=>!v)}>{expanded?'Show fewer components':`Show all ${rows.length} components`}</Button>}</details>
 <p className="equipment-revision">Requirements, candidates, source references and catalogue snapshot identity are included in every design download.</p></>:<p>Equipment matching is ready after the applied RD calculations.</p>}
 </section>;
}
