'use client';
const n=(value:any,digits=1)=>typeof value==='number'&&Number.isFinite(value)?value.toLocaleString(undefined,{maximumFractionDigits:digits}):'Unassigned';
const words=(value:string)=>value.replaceAll('_',' ');
export default function SizingReview({data}:{data?:any}){
 if(!data)return <div className="sizing-intro">Pipe dimensions are manual. Select <strong>Piping → Sizing mode → Preliminary</strong> to calculate flow, catalogue sizes, and rough head/power.</div>;
 const flow=data.thermal_flows;
 return <section className="sizing-review" aria-label="Preliminary sizing results"><h3>Preliminary sizing</h3><p>Prescribed flow · {data.sizing_ready===false?'Some pipe families exceed the catalogue; geometry is a review draft':'Catalogue sizes applied'} · network pressure balancing not performed</p>
 <div className="sizing-metrics"><div><small>LIQUID HEAT</small><strong>{n(flow.liquid_heat_W/1000)} kW</strong></div><div><small>TCS FLOW</small><strong>{n(flow.TCS_L_min)} L/min</strong></div><div><small>TOTAL CHILLER HEAT</small><strong>{n(flow.plant_heat_W/1000)} kW</strong></div><div><small>AIR COIL HEAT</small><strong>{n(flow.air_heat_W/1000)} kW</strong></div><div><small>FACILITY FLOW</small><strong>{n(flow.FWS_L_min)} L/min</strong></div><div><small>IMPLIED TCS RISE</small><strong>{n(flow.effective_TCS_delta_K)} K</strong></div></div>
 <details open><summary>Pipe sizes and Reynolds numbers</summary><p>Flow and the selected velocity limit determine size. Reynolds number and roughness determine the Darcy friction factor. Each pipe family rounds upward through its selected catalogue.</p><div className="sizing-table"><table><thead><tr><th>Pipe family</th><th>Design L/min</th><th>Nominal in</th><th>Actual ID mm</th><th>Limit m/s</th></tr></thead><tbody>{data.size_families.map((f:any)=><tr key={f.family+f.material}><td>{words(f.family)}<small>{words(f.material)}</small></td><td>{n(f.design_flow_m3_s*60000)}</td><td>{n(f.selection?.nominal_size_in,2)}</td><td>{n(f.selection?.id_m*1000,2)}</td><td>{n(f.velocity_cap_m_s,2)}{!f.selection&&<p role="alert">{f.reason}</p>}</td></tr>)}</tbody></table></div></details>
 <details open><summary>Pump duty estimates</summary><p>Routed Darcy–Weisbach loss plus declared fitting K and equipment pressure budgets. Parallel-branch pressure balancing, pump curves, NPSH and operating redundancy remain unverified.</p><div className="sizing-table"><table><thead><tr><th>Equipment / circuit</th><th>Duty L/min</th><th>Head m</th><th>Input kW</th><th>Status</th></tr></thead><tbody>{data.pump_screens.map((p:any)=><tr key={p.component_id+p.circuit_id}><td>{p.component_id}<small>{p.circuit_id}</small></td><td>{n(p.design_flow_m3_s*60000)}</td><td>{n(p.pump_head_m)}</td><td>{n(p.estimated_input_power_W/1000,2)}</td><td>{words(p.status).toLowerCase()}</td></tr>)}</tbody></table></div></details>
 <details><summary>Valve Kv / Cv requirements · {data.valve_capacities.length} valves</summary><p>These are required coefficients at the allocated pressure drop. A manufacturer’s rated Kvs/Cv, authority and operating position must be checked when selecting the valve.</p><div className="sizing-table"><table><thead><tr><th>Valve</th><th>L/min</th><th>Allocated kPa</th><th>Kv m³/h</th><th>Cv US</th></tr></thead><tbody>{data.valve_capacities.map((v:any)=><tr key={v.edge_id}><td>{v.component_id}</td><td>{n(v.flow_m3_s*60000)}</td><td>{n(v.allocated_dp_Pa/1000)}</td><td>{n(v.Kv_m3_h,2)}</td><td>{n(v.Cv_US,2)}</td></tr>)}</tbody></table></div></details>
 <details><summary>Edge calculations and assumptions</summary><p>Fluid density, specific heat, viscosity, generic K values, equipment loss allocations and efficiency are project inputs. Verify them for the selected fluid and mean temperature. Closed-loop elevation is not added as pump static lift; an open tower circuit uses its separate lift and nozzle pressure inputs.</p><div className="sizing-table"><table><thead><tr><th>Component</th><th>m/s</th><th>Re</th><th>Darcy f</th><th>Loss kPa</th><th>Regime</th></tr></thead><tbody>{data.edge_estimates.map((e:any)=><tr key={e.edge_id}><td>{e.component_id}</td><td>{n(e.velocity_m_s,2)}</td><td>{n(e.Reynolds,0)}</td><td>{n(e.friction_factor,4)}</td><td>{n(e.total_dp_Pa==null?null:e.total_dp_Pa/1000,2)}</td><td>{e.flow_regime?words(e.flow_regime):'Unresolved'}</td></tr>)}</tbody></table></div></details>
 {data.unresolved?.length>0&&<details className="sizing-unresolved"><summary>{data.unresolved.length} sizing qualifications</summary>{data.unresolved.map((u:any,i:number)=><p key={i}>{u.component_id||u.edge_id||u.circuit_id||u.code}: {u.detail||u.reason}</p>)}</details>}
 <p className="sizing-source">Methods: <a href="https://handbook.ashrae.org/Handbooks/F25/SI/F25_Ch22/F25_Ch22_si.aspx" target="_blank" rel="noreferrer">ASHRAE Fundamentals 2025, ch. 22</a> · <a href="https://www.opencompute.org/documents/oai-system-liquid-cooling-guidelines-in-ocp-template-mar-3-2023-update-pdf" target="_blank" rel="noreferrer">OCP OAI example, §1.3</a>. Numeric defaults are not universal requirements.</p>
 </section>
}
